/**
 * Executes the Markov chain simulation to determine drop probability distributions.
 * Iteratively multiplies the state vector against the transition matrix to simulate KC progression.
 * * @param {Array<Float64Array>} matrix - The 2D transition matrix generated by the engine.
 * @param {number} targetKC - The user's requested kill count to evaluate.
 * @returns {Object} Statistical milestones and downsampled curve data for Chart.js.
 */
export function runSimulation(matrix, targetKC) {
    const size = matrix.length;
    let v = new Float64Array(size);
    
    // All simulations begin at State 0 (0 items collected) at 0 KC.
    v[0] = 1.0; 

    let prevP = 0, mean = 0, median = 0, modeKC = 0, maxPMF = 0, targetP = 0;

    // Store history in flat arrays rather than pushing object maps on every iteration.
    // This prevents severe memory bloat and garbage collection pauses during long grinds.
    const historyCDF = [0];
    const historyPMF = [0];
    let finalK = 0;

    // Hard cap prevents main-thread lockup if a mathematically impossible matrix is passed.
    for (let k = 1; k < 1000000; k++) {
        let nextV = new Float64Array(size);
        let activeTransientStates = 0;

        // Iterate only through transient (incomplete) states. 
        // The final state is absorbing; calculating transitions OUT of it wastes cycles.
        for (let i = 0; i < size - 1; i++) {
            // Prune microscopic probabilities to bypass floating-point underflow 
            // and significantly accelerate vector multiplication over thousands of kills.
            if (v[i] < 1e-12) continue; 
            
            activeTransientStates++;

            for (let j = i; j < size; j++) {
                if (matrix[i][j] === 0) continue;
                nextV[j] += v[i] * matrix[i][j]; 
            }
        }

        // Manually carry forward the probability mass of the absorbing (completed) state.
        nextV[size - 1] += v[size - 1]; 
        v = nextV;
        
        const currP = v[size - 1];
        const pmf = currP - prevP;
        
        historyCDF.push(currP);
        historyPMF.push(pmf);

        mean += k * pmf;

        if (pmf > maxPMF) {
            maxPMF = pmf;
            modeKC = k;
        }

        if (!median && currP >= 0.5) {
            median = k;
        }

        if (k === targetKC) {
            targetP = currP;
        }

        prevP = currP;
        finalK = k;
        
        // Auto-crop: Terminate early if the player has effectively a 100% chance of completion
        // AND we have processed enough KC past the mean to capture the right-skewed tail for the chart.
        if ((currP > 0.99999 && k > mean * 1.5) || activeTransientStates === 0) {
            break;
        }
    }

    const curveData = [];
    
    // Downsample the result to a maximum of 2500 coordinates. 
    // Passing 50,000+ exact coordinates to Chart.js will cause the browser canvas to freeze.
    const numPoints = 2500; 
    const stepSize = Math.max(1, Math.floor(finalK / numPoints));

    for (let k = 1; k <= finalK; k += stepSize) {
        curveData.push({ x: k, pmf: historyPMF[k], cdf: historyCDF[k] });
    }

    // Ensure critical milestones are explicitly included in the downsampled dataset 
    // so annotation lines and tooltips have exact data coordinates to snap to.
    const milestones = [targetKC, modeKC, median].filter(m => m > 0 && m <= finalK);
    milestones.forEach(m => {
        if (m % stepSize !== 0) {
            curveData.push({ x: m, pmf: historyPMF[m], cdf: historyCDF[m] });
        }
    });

    // Re-sort because injected milestones may be out of order relative to the uniform step sequence.
    curveData.sort((a, b) => a.x - b.x);

    return { targetP, mean, median: median || 0, modeKC, maxPMF, curveData };
}