// ==========================================
// OSRS DROP RATE CALCULATOR - SIMULATION
// ==========================================

// Centralizing our performance and display thresholds
const SIM_CONFIG = {
    MAX_ITERATIONS: 1000000,     // Prevents main-thread lockup on impossible matrices
    PRUNE_THRESHOLD: 1e-12,      // Bypasses underflow calculations on dead states
    COMPLETION_THRESHOLD: 0.99999, // Our effective "100% completion" mark
    TAIL_MULTIPLIER: 1.5,        // How far past the mean we want to draw the chart tail
    MAX_CHART_POINTS: 2500       // Max canvas coordinates before Chart.js stutters
};

/**
 * Helper to compress thousands of simulation iterations into a digestible format for Chart.js.
 * We extract this to keep the main simulation loop focused purely on the math.
 */
function buildChartData(historyPMF, historyCDF, finalK, targetKC, modeKC, median) {
    const curveData = [];
    const stepSize = Math.max(1, Math.floor(finalK / SIM_CONFIG.MAX_CHART_POINTS));

    // Downsample the bulk of the curve based on our step limit
    for (let k = 1; k <= finalK; k += stepSize) {
        curveData.push({ x: k, pmf: historyPMF[k], cdf: historyCDF[k] });
    }

    // Ensure critical milestones are explicitly included in the dataset 
    // so annotation lines and tooltips have exact data coordinates to snap to.
    const milestones = [targetKC, modeKC, median].filter(m => m > 0 && m <= finalK);
    
    milestones.forEach(m => {
        // Only inject if it wasn't already caught by our uniform step jump
        if (m % stepSize !== 0) {
            curveData.push({ x: m, pmf: historyPMF[m], cdf: historyCDF[m] });
        }
    });

    // Re-sort because injected milestones may be out of order relative to the step sequence.
    curveData.sort((a, b) => a.x - b.x);

    return curveData;
}

/**
 * Executes the Markov chain simulation to determine drop probability distributions.
 * Iteratively multiplies the state vector against the transition matrix to simulate KC progression.
 * * @param {Array<Float64Array>} matrix - The 2D transition matrix generated by the engine.
 * @param {number} targetKC - The user's requested kill count to evaluate.
 * @returns {Object} Statistical milestones and downsampled curve data for Chart.js.
 */
export function runSimulation(matrix, targetKC) {
    const size = matrix.length;
    const absorbingState = size - 1; // The final state where all items are collected
    
    let stateVector = new Float64Array(size);
    stateVector[0] = 1.0; // All simulations begin at State 0 (0 items collected) at 0 KC.

    let prevCDF = 0, mean = 0, median = 0, modeKC = 0, maxPMF = 0, targetP = 0;

    // Store history in flat arrays rather than pushing object maps on every iteration.
    // This prevents severe memory bloat and garbage collection pauses during long grinds.
    const historyCDF = [0];
    const historyPMF = [0];
    let finalK = 0;

    for (let k = 1; k < SIM_CONFIG.MAX_ITERATIONS; k++) {
        let nextStateVector = new Float64Array(size);
        let activeTransientStates = 0;

        // Iterate only through transient (incomplete) states. 
        // Calculating transitions OUT of the completed state wastes cycles.
        for (let i = 0; i < absorbingState; i++) {
            
            // Prune microscopic probabilities to accelerate vector multiplication
            if (stateVector[i] < SIM_CONFIG.PRUNE_THRESHOLD) continue; 
            
            activeTransientStates++;

            for (let j = i; j < size; j++) {
                if (matrix[i][j] === 0) continue;
                nextStateVector[j] += stateVector[i] * matrix[i][j]; 
            }
        }

        // Manually carry forward the probability mass of the absorbing state.
        nextStateVector[absorbingState] += stateVector[absorbingState]; 
        stateVector = nextStateVector;
        
        const currCDF = stateVector[absorbingState];
        const currPMF = currCDF - prevCDF;
        
        historyCDF.push(currCDF);
        historyPMF.push(currPMF);

        mean += k * currPMF;

        if (currPMF > maxPMF) {
            maxPMF = currPMF;
            modeKC = k;
        }

        if (!median && currCDF >= 0.5) {
            median = k;
        }

        if (k === targetKC) {
            targetP = currCDF;
        }

        prevCDF = currCDF;
        finalK = k;
        
        // Auto-crop: Terminate early if the player has effectively a 100% chance of completion
        // AND we have processed enough KC past the mean to capture the right-skewed tail.
        if ((currCDF > SIM_CONFIG.COMPLETION_THRESHOLD && k > mean * SIM_CONFIG.TAIL_MULTIPLIER) || activeTransientStates === 0) {
            break;
        }
    }

    const curveData = buildChartData(historyPMF, historyCDF, finalK, targetKC, modeKC, median);

    return { targetP, mean, median: median || 0, modeKC, maxPMF, curveData };
}